# Generated by Django 3.2.7 on 2021-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tejido',
            name='inflammation',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
