# Generated by Django 3.2.7 on 2021-11-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tejido_inflammation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tejido',
            name='inflammation',
            field=models.FloatField(verbose_name='Inflamación'),
        ),
        migrations.AlterField(
            model_name='tejido',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.paciente'),
        ),
    ]
